# Generated by Django 4.0.3 on 2022-11-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_instituteprofile_act_name_instituteprofile_logo_name'),
        ('Lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlecturer',
            name='institute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Institute.instituteprofile'),
            preserve_default=False,
        ),
    ]
