# Generated by Django 4.0.3 on 2022-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlecturer',
            name='act_url',
            field=models.CharField(default=0, max_length=100, verbose_name='Act Url'),
            preserve_default=False,
        ),
    ]
