# Generated by Django 4.0.3 on 2022-11-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0002_headlecturer_act_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlecturer',
            name='profile_url',
            field=models.CharField(default=0, max_length=100, verbose_name='Profile Url'),
            preserve_default=False,
        ),
    ]
