# Generated by Django 4.0.3 on 2022-11-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Institute', '0001_initial'),
        ('Lecturer', '0003_headlecturer_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_name', models.CharField(max_length=40, verbose_name='Lecturer Name')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('profile_image', models.ImageField(default='instituteIc.png', upload_to='Profile', verbose_name='Profile')),
                ('profile_url', models.CharField(max_length=100, verbose_name='Profile Url')),
                ('profile_image_name', models.CharField(default='instituteIc.png', max_length=40, verbose_name='Profile Source')),
                ('act', models.ImageField(default='actIc.png', upload_to='Activity', verbose_name='Activity Image')),
                ('act_url', models.CharField(max_length=100, verbose_name='Act Url')),
                ('act_name', models.CharField(default='actIc.png', max_length=40, verbose_name='Activity Source')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecturer.department')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.instituteprofile')),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
