# Generated by Django 4.0.3 on 2022-11-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0004_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Lecturer.department'),
            preserve_default=False,
        ),
    ]
