# Generated by Django 4.0.3 on 2022-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0005_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_desc',
            field=models.TextField(default=0, verbose_name='Course Bio'),
            preserve_default=False,
        ),
    ]
