# Generated by Django 4.0.3 on 2022-11-07 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=40, verbose_name='Category Name')),
                ('cate_description', models.TextField(verbose_name='Category Description')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40, verbose_name='Company Name')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('vission', models.TextField(verbose_name='Vision')),
                ('logo', models.ImageField(default='instituteIc.png', upload_to='Logos', verbose_name='Logo')),
                ('logo_name', models.CharField(default='instituteIc.png', max_length=40, verbose_name='Logo Source')),
                ('act', models.ImageField(default='actIc.png', upload_to='Activity', verbose_name='Activity Image')),
                ('act_name', models.CharField(default='actIc.png', max_length=40, verbose_name='Activity Source')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('company_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('county', models.CharField(max_length=20, verbose_name='County')),
                ('town', models.CharField(max_length=20, verbose_name='Town')),
                ('latitude', models.CharField(max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='Longitude')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('comp_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.category')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofile')),
            ],
        ),
    ]
