# Generated by Django 4.0.3 on 2022-11-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_cv_name_student_rec_name_student_stud_phone'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.job')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('job_app_id', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.ManyToManyField(blank=True, related_name='accepted_applicants', to='Student.student', verbose_name='Accepted Applicants')),
                ('applicants', models.ManyToManyField(blank=True, related_name='new_applicants', to='Student.student', verbose_name='All Applicants')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofile', verbose_name='Company')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.job', verbose_name='Job')),
            ],
        ),
    ]
