# Generated by Django 4.0.3 on 2022-11-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('job_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_level_name', models.CharField(max_length=50, verbose_name='Job Location Name')),
                ('job_level_decription', models.TextField(verbose_name='Job Location Description')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('job_loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_loc_name', models.CharField(max_length=50, verbose_name='Job Location Name')),
                ('job_location_decription', models.TextField(verbose_name='Job Location Description')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofile')),
            ],
        ),
    ]
