# Generated by Django 4.0.3 on 2022-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companycategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='act_name',
            field=models.CharField(default='actIc.png', max_length=40, verbose_name='Activity Source'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_name',
            field=models.CharField(default='instituteIc.png', max_length=40, verbose_name='Logo Source'),
        ),
    ]
