# Generated by Django 4.0.3 on 2022-11-10 11:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_joblevel_joblocation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_decr',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Company.joblevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Company.joblocation'),
            preserve_default=False,
        ),
    ]
