# Generated by Django 4.0.3 on 2022-11-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_job_job_decr_job_job_level_job_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job', to='Company.companyprofile'),
        ),
    ]
