# Generated by Django 4.0.3 on 2022-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_companyprofile_act_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylocation',
            name='latitude',
            field=models.TextField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='longitude',
            field=models.TextField(verbose_name='Longitude'),
        ),
    ]
