# Generated by Django 4.0.3 on 2022-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_companylocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylocation',
            name='latitude',
            field=models.CharField(max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='longitude',
            field=models.CharField(max_length=20, verbose_name='Longitude'),
        ),
    ]
