# Generated by Django 4.0.3 on 2022-11-15 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lecturer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=40, verbose_name='Student Name')),
                ('profile_image', models.ImageField(default='instituteIc.png', upload_to='Profile', verbose_name='Profile')),
                ('profile_image_name', models.CharField(default='instituteIc.png', max_length=40, verbose_name='Profile Source')),
                ('act', models.ImageField(default='actIc.png', upload_to='Activity', verbose_name='Activity Image')),
                ('act_name', models.CharField(default='actIc.png', max_length=40, verbose_name='Activity Source')),
                ('cv', models.FileField(upload_to='Files', verbose_name='CV')),
                ('rec', models.FileField(upload_to='Files', verbose_name='Recommendation Letter')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.department')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.instituteprofile')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
