# Generated by Django 4.0.3 on 2022-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv_name',
            field=models.CharField(default=0, max_length=40, verbose_name='CV Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rec_name',
            field=models.CharField(default=0, max_length=40, verbose_name='Recommend Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stud_phone',
            field=models.CharField(default=0, max_length=40, verbose_name='Student Phone'),
            preserve_default=False,
        ),
    ]
