# Generated by Django 4.0.3 on 2022-12-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0006_course_course_desc'),
        ('Student', '0002_student_cv_name_student_rec_name_student_stud_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadConnect',
            fields=[
                ('head_connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Lecturer.headlecturer')),
                ('students', models.ManyToManyField(blank=True, to='Student.student', verbose_name='All Connects')),
            ],
        ),
    ]
