# Generated by Django 4.0.3 on 2022-12-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0006_course_course_desc'),
        ('Student', '0003_headconnect'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLec',
            fields=[
                ('student_lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('connected', models.BooleanField(default=False, verbose_name='Connection')),
                ('whom', models.CharField(choices=[('none', 'NONE'), ('head', 'HEAD'), ('lecturer', 'LECTURER')], default='none', max_length=12)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.headlecturer', verbose_name='Department Head')),
                ('lec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.lecturer', verbose_name='Lecturer')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='Student')),
            ],
        ),
    ]
