# Generated by Django 4.0.3 on 2022-12-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0006_course_course_desc'),
        ('Student', '0004_studentlec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlec',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.headlecturer', verbose_name='Department Head'),
        ),
        migrations.AlterField(
            model_name='studentlec',
            name='lec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecturer.lecturer', verbose_name='Lecturer'),
        ),
    ]
