# Generated by Django 4.0.3 on 2022-12-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_studentlec_head_alter_studentlec_lec'),
    ]

    operations = [
        migrations.AddField(
            model_name='headconnect',
            name='acc_students',
            field=models.ManyToManyField(blank=True, related_name='student_Request_accepted', to='Student.student', verbose_name='Accepted Connects'),
        ),
        migrations.AlterField(
            model_name='headconnect',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_Request', to='Student.student', verbose_name='New Connects'),
        ),
    ]
