# Generated by Django 4.0.3 on 2023-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_headconnect_acc_students_alter_headconnect_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlec',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
