# Generated by Django 4.0.3 on 2022-11-07 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('institute_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=40, verbose_name='Institute Name')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('vission', models.TextField(verbose_name='Vision')),
                ('logo', models.ImageField(default='instituteIc.png', upload_to='Logos', verbose_name='Logo')),
                ('act', models.ImageField(default='actIc.png', upload_to='Activity', verbose_name='Activity Image')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteLocation',
            fields=[
                ('institute_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('county', models.CharField(max_length=20, verbose_name='County')),
                ('town', models.CharField(max_length=20, verbose_name='Town')),
                ('latitude', models.CharField(max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='Longitude')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
