# Generated by Django 4.0.3 on 2022-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprofile',
            name='act_name',
            field=models.CharField(default='actIc.png', max_length=40, verbose_name='Activity Source'),
        ),
        migrations.AddField(
            model_name='instituteprofile',
            name='logo_name',
            field=models.CharField(default='instituteIc.png', max_length=40, verbose_name='Logo Source'),
        ),
    ]
